// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAar0MIBB8obYq8CA_w_wFd07IAZz6sOag',
    appId: '1:7401762086:web:ba33414bd6f65a98d725e7',
    messagingSenderId: '7401762086',
    projectId: 'studio-5568421099-903f6',
    authDomain: 'studio-5568421099-903f6.firebaseapp.com',
    storageBucket: 'studio-5568421099-903f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe1hFneu62bdCqEZF5LO2ttI_pfXfCJkk',
    appId: '1:7401762086:android:e40862b6d5405da7d725e7',
    messagingSenderId: '7401762086',
    projectId: 'studio-5568421099-903f6',
    storageBucket: 'studio-5568421099-903f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyhVtWFaSvPdHcS-Jc66C-E0USAs310os',
    appId: '1:7401762086:ios:dd82985db21fb695d725e7',
    messagingSenderId: '7401762086',
    projectId: 'studio-5568421099-903f6',
    storageBucket: 'studio-5568421099-903f6.firebasestorage.app',
    iosClientId: '7401762086-pec1ml7q6vdf8qo9rr5j3krrl1iprjlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyhVtWFaSvPdHcS-Jc66C-E0USAs310os',
    appId: '1:7401762086:ios:dd82985db21fb695d725e7',
    messagingSenderId: '7401762086',
    projectId: 'studio-5568421099-903f6',
    storageBucket: 'studio-5568421099-903f6.firebasestorage.app',
    iosClientId: '7401762086-pec1ml7q6vdf8qo9rr5j3krrl1iprjlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAar0MIBB8obYq8CA_w_wFd07IAZz6sOag',
    appId: '1:7401762086:web:4ee125deb2ccb70ed725e7',
    messagingSenderId: '7401762086',
    projectId: 'studio-5568421099-903f6',
    authDomain: 'studio-5568421099-903f6.firebaseapp.com',
    storageBucket: 'studio-5568421099-903f6.firebasestorage.app',
  );
}
